### PR TITLE
(change) take arity argument out of argument list.

### PR DESCRIPTION
**Pull request by ottonascarella**
Hi there,
Just thought currying would be more flexible if auto arity could take place.

### CODE REVIEW

**Comment by ottonascarella** [comment]
hey...my bad.

should have read the docs before pulling. still...that's my humble suggestion.

**Comment by ottonascarella** [comment]
(just also realized you depend on that arg on other places....oooops.

**Comment by robotlolita** [comment]
Oh, hello.

Thanks for the time you put into writing this PR. I'm not merging it because it goes against some goals in Folktale, and in particular makes composing (curried) functions more confusing. It would be great if we could infer the arity automatically for currying. Sadly, that's a bit difficult in JavaScript for a few reasons.

The `length` property returns the number of syntactically-provided formal parameters, not the amount of *intended* parameters the function wants to receive in order to do work. This means that in a lot of cases, the value represented in `length` isn't the number of arguments you need to pass.

For example:

```js
// rests are not counted
const sum = (...xs) => xs.reduce((a, b) => a + b, 0);
sum.length  // ==> 0 (intended: maybe 2)

// optionals are not counted
const foo = (a, b = someDefault) => a * b;
foo.length  // ==> 1 (intended: 2)

// messing up with `arguments` is not counted
function bar() {
  const x = arguments[0], y = arguments[1], z = isObject(y) ? arguments[2] : {};
}
bar.length // ==> 0 (intended: 2 or 3)
```

While one could argue that variadic/optionals shouldn't be supported, the problem is that JavaScript code often relies a lot on transforming functions. And since `.length` only looks at the syntactically-provided formal parameters, it has no way of reflecting the original intention of those functions.

For example:

```js
const flip = (f, a, b) => f(b, a);
flip.length // ==> 3 (intended: 3)
curry(flip)((x, y) => x - y)(2)(3); // ==> 1

// If we transform `flip` for any reason, things start looking not so good
const cflip = curry(flip);
curry(cflip)(2)(3); // ==> NaN is not a function
cflip.length // ==> 0
```    

Because functional programming also encourages a lot of function composition, and Folktale's internal code certainly uses a lot of it, these cases tend to be fairly common except for when you're currying a static function definition. Having something that works in a particular context, but may or may not work in another context is very confusing. One would assume that, if `curry(f)` works, then `curry(g(f))` should also work, if `g(f)` returns a function that has the same intended number of parameters as `f`.

This is even worse in functions like `partialise`, which despite having a fixed number of arguments, has to rely on `arguments` internally, as it would otherwise need to generate JavaScript code and ask the interpreter to evaluate that in order to keep the `.length` property in sync with the intended number of arguments. Or do what Ramda does, for a fixed number of arguments: https://github.com/ramda/ramda/blob/master/src/internal/_arity.js. 

Ramda's function is also internal, so it doesn't help users who may face the same problem when composing their own functions. That's not good. Neither of the two approaches are very compelling for simplicity, maintenance, performance, or security :(

One of the goals of Folktale 2 is to reduce the number of features that may be confusing to users, and encourage the usage of features that are simpler and more straight-forward (to both understand and debug). That's also one of the reasons we don't use `curry` by default anymore — `curry` alone is confusing when you mix in variadic functions. Adding arity inference, even if optional (like Ramda does), makes it more confusing.

**Comment by ottonascarella** [comment]
I realized all that right after pushing the button.

I promise next time I submit a patch, it would be after actually reading all the README content! (I feel so dumb for not having done that!)

Your code has been a great inspiration.
Thanks for your thorough explanation, and for the amazing work with the library.

**Pull request closed without merging**
