### PR TITLE
Conversions

### PR DESCRIPTION
**Pull request by boris-marinov**
Includes 

1. A Conversions module which consists of six functions of type `X -> Y` which convert each of the three types `Maybe`, `Either` and `Validation` to all other types. The module is private (it is not exported in `data`). The functions for converting a `Maybe` to an `Either` or `Validation` accept as a second parameter the error value which is to be put in the `Either`/`Validation` in case the first parameter is `Nothing`.

2. Aliases to all of the module's functions as part of the type definitions (so `Either.fromValidation` is an alias to `validationToEither`).

3. Methods for converting an instance to another one which call the above function (so `Left(1).toEither()` is `leftToEither(Left(1))`). This introduces a circular dependency which is resolved by requiring the helper functions after the type definition is exported in the `core.js` files for all datatypes.

### CODE REVIEW

**Comment by robotlolita** [comment]
Ah, that's neat :+1: 

Instead of putting the `require`s at the bottom and relying on Node's caching (which I'm not too fond of), we can just move those requires inside of the function. Like:

```js
Maybe.toEither = function(...args) {
  return require('folktale/data/conversions/maybe-to-either')(this, ...args);
};
```

Since these are not resolved eagerly, mutual recursion just works. Caching solves the loading problem if people call it many times.

**Comment by boris-marinov** [comment]
Done.

**Comment by robotlolita** [comment]
LGTM. Could you move `fromNullable` to `data/conversions` and add one for Either as well?

**Comment by boris-marinov** [comment]
Good idea.

**Comment by robotlolita** [comment]
Thanks :)

I suppose this has to wait Validation to be merged now.

**Comment by robotlolita** [comment]
Could you rebase this on master?

**Comment by boris-marinov** [comment]
oops I think I messed it up. 
I will pull from master and try to rebase again.
sorry.

**Comment by boris-marinov** [comment]
I redid the changes in another branch:
https://github.com/origamitower/folktale/tree/conversions-redone

**Comment by robotlolita** [comment]
Thanks :)

**Pull request closed without merging**
