### PR TITLE
Conversion from nodeback to task

### PR DESCRIPTION
**Pull request by rpearce**
_This is my first foray into this project, so please be gentle!_

Couple of housekeeping things:
  * I'm not sure what to put in the `type` magic doc field for this. Could you help me understand that better?
  * I did my best to conform to your code style on this one. Any changes required?
  * is this happy-path test enough? what else would you like to see?
```
describe('#fromNodeback', () => {
  it('Returns a task when given a nodeback-style function', () => {
    let resultStr = 'test';
    const fn = (str, cb) => cb(str + '-processed');
    const convertedFn = Task.fromNodeback(fn);
    const appliedFn = convertedFn(resultStr, (str) => {
      resultStr = str;
    });

    appliedFn.run();

    $ASSERT(resultStr === 'test-processed');
  });
});
```

This closes https://github.com/origamitower/folktale/issues/96

EDIT: I've noticed this deleted a lot of files... looking at it. I only ran the `make` commands as specified in the docs
EDIT2: it also looks like I need to update my commit message stuff. Argh. Any guidance is appreciated.

## To Do
- [x] write documentation
- [x] update commit message
- [x] un-delete docs files(?)
- [x] add spec for resolving successfully with a value
- [x] add spec for error case

### CODE REVIEW

**Comment by robotlolita** [comment]
screenshot from 2017-04-25 20-10-17

Thanks for the time in putting together this PR :)

Ah, yeah, the Make commands will delete the generated documentation :x You can regenerate it with `make documentation`. I have to move these to the gh-pages branch :x

As for the git commit message, you can rebase after you're done and reword/squash your commits as needed. Don't worry too much about it though :)

- - -

So, on to the other things.

The `type` documentation field is pretty much a description of how the inputs and outputs like following [this notation](https://github.com/origamitower/folktale/blob/master/docs/source/en/guides/annexes/0-type-notation.md). In this case, the types would look like this:

```
forall s, e, r:
((Any..., (e, s) => Void) => Void)
=> (Any...)
=> Task e s r
```

Where `s` is the success value, `e` is the error, and `r` is a [resource type](https://github.com/origamitower/folktale/pull/94#issuecomment-287964019).

The style is a-okay :) I've added a couple of notes on the patch.

**Comment by rpearce** [comment]
@robotlolita thank you! Where can I see these notes you referenced?

I'll be getting to this in a few hours. Thanks again

**Comment by robotlolita** [comment]
@rpearce oh right, it doesn't show up if I don't submit them. Sorry about that :')

**Comment by rpearce** [comment]
@robotlolita mind taking another look at this? The commit message, tests, and all the rest should meet the requirements now!

**Comment by robotlolita** [comment]
Thanksies :)

**Pull request merged**
